version = "Two"
max_width = 90
use_small_heuristics = "Max" # Replace with the one below when rustfmt hits 2.0
#width_heuristics = "Max"
hard_tabs = true
newline_style = "Unix"
imports_layout = "HorizontalVertical"
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
error_on_unformatted = true
format_code_in_doc_comments = true
